### ISSUE TITLE
Transcript based test running spec

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-FunctionalTests#137]
In order to be able to run transcript based function tests against a given bot we will need to create a test runner, this issue involves creating the initial spec.

**Comment by mrivera-ms** [comment]
This is in progress [here](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/specs/TransciptTestRunner.md), and will continue iterating in future milestones. It is being removed from R11 because it is not meant to complete within this milestone.

**Comment by mrivera-ms** [comment]
The testrunner is in execution mode. Closing this as no longer needed. @gabog , please reopen it if you think it is necessary.
