### ISSUE TITLE
Write TranscriptConverter

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/BotFramework-FunctionalTests#143]
**TranscriptConverter** is part of the test runner effort meant to revamp the FunctionalTests capabilities in this repo. The spec is in development [here](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/specs/TransciptTestRunner.md).

This component is still in development, but preliminary, the following parts are needed:

**Methods**

- **Convert** - _Inputs:_ and Emulator transcript; - _Output:_ a "test script"

Tentatively, the test script will contain all properties of the Emulator transcript minus variable GUIDs like Id fields and date/time fields. 

The Convert methods should deserialize the input, remove the undesired fields and serialize again.

**Comment by gabog** [comment]
The first pass of this one is done, closing it, we will create specific ones for missing functionality later if needed.
