### ISSUE TITLE
Update some csproj files to match folder names

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-FunctionalTests#168]
I am trying to create a dotnet solution that contains all the projects under Bots/DotNet and I can't because some projects have the same name. The ask here is to rename some csproj in the functionaltestsstaging branch as follows:

- [x] Rename Bots\DotNet\Consumers\CodeFirst\SimpleHostBot-2.1\SimpleHostBot.csproj to Bots\DotNet\Consumers\CodeFirst\SimpleHostBot-2.1\SimpleHostBot-2.1.csproj
- [x] Rename  DotNet\Skills\CodeFirst\EchoSkillBot-2.1\EchoSkillBot.csproj to DotNet\Skills\CodeFirst\EchoSkillBot-2.1\EchoSkillBot-2.1.csproj
- [x] Rename Bots\DotNet\Skills\CodeFirst\EchoSkillBot-v3\EchoSkillBot.csproj Bots\DotNet\Skills\CodeFirst\EchoSkillBot-v3\EchoSkillBot-v3.csproj
- [x] Update related yaml files as needed.

**Comment by gabog** [comment]
@denscollo, @ceciliaavila, @JuanAr, would you guys be able to address this one?

Thanks

**Comment by denscollo** [comment]
@gabog Sure! We'll add it to our iteration backlog!  Thanks
