### ISSUE TITLE
Refactor CI/CD pipeline

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-FunctionalTests#183]
We need to refactor the CI/CD pipeline so we can:
1. Have a manually triggered pipeline that deploys and configures a shared resource group with common components used by all the bots:
  App Service Plan
  CosmosDB
  AppInsights

2. Have a pipeline that provisions all the consumer and skills at once and then executes the test cases in a configure/test loop that should run for each scenario.

Here is a draft diagram that outlines the deployment once is done:
![image](https://user-images.githubusercontent.com/12264946/99882944-f73cc600-2bf1-11eb-9692-322b5150ee73.png)

**Comment by gabog** [comment]
We just need to add the Python bots to the pipeline and we can close this one.

**Comment by denscollo** [comment]
Hi @gabog we added 1 more PR, besides the Python Support one, that goes with the refactor of the CI/CD pipeline, which is #262  **Get Bot AppId from KeyVault in Test Scenarios pipeline**

**Comment by ceciliaavila** [comment]
Solved.
