### ISSUE TITLE
Python bots failing in deployment step

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/BotFramework-FunctionalTests#199]
## Describe the bug
All python bots fail to deploy.

## To Reproduce
The error is visible in the any of the pipelines that deploy Python bots. A couple of samples:

- [DotNet21PySkillBotFunctionalTest](https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=913)
- [JsPySkillBotFunctionalTest](https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=870)

## Error Information
The error happens in this line: [pythonDeployStepsNewRG.yml#L109](https://github.com/microsoft/BotFramework-FunctionalTests/blob/a3fdd1f4917bc6ed52feb8efe6825a648f78526d/build/yaml/pythonDeployStepsNewRG.yml#L109)

The error message: `fatal: unable to access 'https://NightlyDotNet21PySkillBot-192768.scm.azurewebsites.net:443/NightlyDotNet21PySkillBot-192768.git/': The requested URL returned error: 403`

Let's explore the option to remove the git deployment and instead, use the recommended method [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=python#option-1-existing-app-service-plan).

**Comment by gabog** [comment]
This has been fixed, closing
