### ISSUE TITLE
Update waterfall bots to support expect replies and update/create tests

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-FunctionalTests#259]
This issue involves:

- [x] Updating the waterfall host to ask for delivery mode
- [x] Updating existing tests
- [x] Updating pipeline
- [x] Adding SignIn and FileUpload tests

**Comment by gabog** [comment]
Hi @denscollo, @ceciliaavila, the three PRs are now merged, can we close this issue? (just close it if the answer is yes :)).

**Comment by ceciliaavila** [comment]
> Hi @denscollo, @ceciliaavila, the three PRs are now merged, can we close this issue? (just close it if the answer is yes :)).

We still have pending the new tests for Waterfall (SignIn, FileUpload), but we could address those in a different issue.

**Comment by gabog** [comment]
Let's use this one then (no need to create a new issue)

**Comment by gabog** [comment]
@denscollo / @ceciliaavila, I think this one is done, can I close it?

Thanks

**Comment by ceciliaavila** [comment]
> @denscollo / @ceciliaavila, I think this one is done, can I close it?
> 
> Thanks

Hi @gabog, yes, it can be closed. Thanks!
