### ISSUE TITLE
Failure in Creating resources  pipelines for skill functional test. Please see the below logs

### ISSUE THREAD

**Issue by anumoluharish** [microsoft/BotFramework-FunctionalTests#288]
1)ERROR: {"error":{"code":"DeploymentActive","message":"Unable to edit or replace deployment 'bffnbotstatedb': previous deployment from '2/4/2021 5:06:41 PM' is still active (expiration time is '2/11/2021 5:06:35 PM'). Please see https://aka.ms/arm-deploy for usage details."}}.

2)##[warning]NuGet Security Analysis found 3 vulnerable nuget.config files in the repository. Builds with this vulnerability will break in the future. Visit https://aka.ms/nugetmultifeed for more details.

3)ERROR: {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'bffnbotsappservicewin' is not valid according to the validation procedure. The tracking id is '2db823ad-afe0-447e-83fa-69516ba566b2'. See inner errors for details.","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"BadRequest","message":"The parameter SKU.Name has an invalid value."}]}]}}

## Screenshots
![image](https://user-images.githubusercontent.com/77343388/106935879-83cf2e80-66e1-11eb-917c-36f9a246bb57.png)
![image](https://user-images.githubusercontent.com/77343388/106936427-2b4c6100-66e2-11eb-9efe-f28df743dce1.png)
![image](https://user-images.githubusercontent.com/77343388/106936659-7797a100-66e2-11eb-8af9-96d6b940c6f5.png)
![image](https://user-images.githubusercontent.com/77343388/106942253-93eb0c00-66e9-11eb-9f5e-42a0cb81945d.png)

**Comment by ceciliaavila** [comment]
Hi @anumoluharish,
1) This error seems to be related to the impossibility of creating a cosmosdb or a keyvault with the same name in different organizations. We were running some tests that may have conflicted with your execution.
Please, delete the resources if they exist in Azure and then run the pipeline again.
2) This warning is solved in main. The staging branch was merged to main so you can configure the pipelines in the main branch.
3) This error seems to be related to an invalid value in the `AppServicePlanPricingTier` variable. You should use 'S1'.

Please, let us know if the issues were solved and if you need anything else.
Thanks.

**Comment by anumoluharish** [comment]
HI @ceciliaavila 

Rerun the pipeline after making changes now it was failing at app registration.

![image](https://user-images.githubusercontent.com/77343388/106944998-e7ab2480-66ec-11eb-8fc3-e9e7a91a46de.png)


Thanks
Harish

**Comment by ceciliaavila** [comment]
To be able to create AppRegistrations, the service principal needs to have **Application.ReadWrite.OwnedBy** permissions ([link](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http#permissions)).

![image](https://user-images.githubusercontent.com/44245136/106945570-bccdca00-6706-11eb-86d8-da5f02004457.png)

**Comment by gabog** [comment]
This one is resolved, closing
