### ISSUE TITLE
End to end testing CloudAdapter

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotFramework-FunctionalTests#323]
We need end to end testing for all scenarios with CloudAdapter:

- oauth prompt
- streaming
- streaming with oauth prompt
- a skill built with CloudAdapter (not the parent just the skill). GG update, this one is being tracked as part of #358)
- a skill with oauth prompt
- oauth input (adaptive version of oauth prompt)

**Comment by gabog** [comment]
Assigning this one to me so we can break it down in smaller issues
