### ISSUE TITLE
[Skills Everywhere] Test SSO functionality after BB-DotNet Token related issues are solved

### ISSUE THREAD

**Issue by denscollo** [microsoft/BotFramework-FunctionalTests#385]
## Description
The SSO functionality needs to be tested once the following **BB-DotNet** issues are solved.
- [#5460](https://github.com/microsoft/botbuilder-dotnet/issues/5460) 
- [#1631](https://github.com/microsoft/botbuilder-python/issues/1631)

These issues were found while testing TokenExchangeSkillHandler port to JS and Python.
- Port to JS: [#368](https://github.com/microsoft/BotFramework-FunctionalTests/pull/368)
- Port to Python: [#369](https://github.com/microsoft/BotFramework-FunctionalTests/pull/369)

**Comment by ceciliaavila** [comment]
SSO tested and working.
