### ISSUE TITLE
[Skills Everywhere] Test Waterfall Skill Bot Python with anonymous authentication 

### ISSUE THREAD

**Issue by ceciliaavila** [microsoft/BotFramework-FunctionalTests#427]
## Description
The WaterfallSkillBotPython needs to be tested locally with no credentials set once the following **BB-Python** issue is solved.
- [#1683](https://github.com/microsoft/botbuilder-python/issues/1683) 

This issue was found while fixing the 404 errors in the Skills Functional Tests.
- [#426](https://github.com/microsoft/BotFramework-FunctionalTests/pull/426)

**Comment by johnataylor** [comment]
@ceciliaavila any update on this?

**Comment by ceciliaavila** [comment]
> @ceciliaavila any update on this?

Hi @johnataylor, the [fix in BotBuilder-Python](https://github.com/microsoft/botbuilder-python/pull/1684) is not merged yet. Once that PR gets merged, we can test the bot and close this issue.

**Comment by ceciliaavila** [comment]
We tested the python bots (host and skill) and they worked as expected using anonymous authentication.
![image](https://user-images.githubusercontent.com/44245136/122404366-8bd39080-cf55-11eb-979b-3342a825275b.png)
